version: "3.9"

services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - express_db_network
    ports:
      - '5432:5432'

networks:
  express_db_network:
    name: express_db_network
    external: true

volumes:
  db-data:
